/* The following code was generated by JFlex 1.4.1 on 12/10/11 12:34 PM */

import java_cup.runtime.SymbolFactory;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 12/10/11 12:34 PM from the specification file
 * <tt>lexico.flex</tt>
 */
class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  8,  6,  0,  0,  7,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     8,  0,  9,  0,  5,  5,  0, 38, 30, 31, 27, 26, 24,  2,  3, 28, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0, 10, 35, 25, 36,  0, 
     0, 16,  4,  4, 13, 11, 21, 19, 37, 14,  4,  4, 22, 15, 12, 23, 
    32,  4, 20, 17, 18, 33,  4,  4, 34,  4,  4,  0,  0,  0, 29,  0, 
     0,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 
     4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\1\1\7\12\4\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\4\1\20\1\21\1\22\1\0"+
    "\1\5\1\0\1\23\3\4\1\24\2\4\1\25\1\4"+
    "\1\26\1\4\1\27\4\4\1\30\1\4\1\31\1\32"+
    "\1\33\1\22\1\2\1\34\2\4\1\35\2\4\1\36"+
    "\5\4\1\37\1\4\1\22\1\4\1\40\1\41\2\4"+
    "\1\42\1\4\1\43\1\44\2\4\1\45\1\4\1\46"+
    "\1\4\1\44\1\47\1\50\1\4\1\51\1\44\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\234\0\303\0\352\0\u0111"+
    "\0\u0138\0\47\0\u015f\0\u0186\0\u01ad\0\u01d4\0\u01fb\0\u0222"+
    "\0\u0249\0\u0270\0\u0297\0\u02be\0\47\0\47\0\47\0\47"+
    "\0\47\0\47\0\47\0\47\0\u02e5\0\u030c\0\u0333\0\u035a"+
    "\0\u0381\0\47\0\u0138\0\u0138\0\u03a8\0\u03cf\0\u03f6\0\234"+
    "\0\u041d\0\u0444\0\234\0\u046b\0\234\0\u0492\0\234\0\u04b9"+
    "\0\u04e0\0\u0507\0\u052e\0\234\0\u0555\0\47\0\47\0\47"+
    "\0\u057c\0\u0381\0\u05a3\0\u05ca\0\u05f1\0\234\0\u0618\0\u063f"+
    "\0\234\0\u0666\0\u068d\0\u06b4\0\u06db\0\u0702\0\234\0\u0729"+
    "\0\47\0\u0750\0\234\0\234\0\u0777\0\u079e\0\234\0\u07c5"+
    "\0\234\0\u07ec\0\u0813\0\u083a\0\234\0\u0861\0\234\0\u0888"+
    "\0\u08af\0\234\0\234\0\u08d6\0\234\0\47\0\234";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\2\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\5"+
    "\1\17\1\20\1\21\1\5\1\22\1\23\1\5\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\2\5\1\36\1\37\1\5\1\40\50\0\1\3"+
    "\1\0\1\41\44\0\1\3\46\0\1\5\1\0\3\5"+
    "\5\0\15\5\10\0\3\5\2\0\1\5\10\0\1\42"+
    "\45\0\1\42\50\0\1\10\36\0\6\43\1\0\2\43"+
    "\1\44\1\0\34\43\1\0\1\5\1\0\3\5\5\0"+
    "\1\5\1\45\11\5\1\46\1\5\10\0\3\5\2\0"+
    "\1\5\2\0\1\5\1\0\3\5\5\0\1\47\13\5"+
    "\1\50\10\0\3\5\2\0\1\5\2\0\1\5\1\0"+
    "\3\5\5\0\3\5\1\51\11\5\10\0\3\5\2\0"+
    "\1\5\2\0\1\5\1\0\3\5\5\0\1\5\1\52"+
    "\10\5\1\53\2\5\10\0\3\5\2\0\1\5\2\0"+
    "\1\5\1\0\3\5\5\0\1\5\1\54\4\5\1\55"+
    "\6\5\10\0\3\5\2\0\1\5\2\0\1\5\1\0"+
    "\3\5\5\0\7\5\1\56\5\5\10\0\3\5\2\0"+
    "\1\5\2\0\1\5\1\0\3\5\5\0\14\5\1\57"+
    "\10\0\3\5\2\0\1\60\2\0\1\5\1\0\3\5"+
    "\5\0\1\61\14\5\10\0\3\5\2\0\1\5\2\0"+
    "\1\5\1\0\3\5\5\0\13\5\1\62\1\63\10\0"+
    "\3\5\2\0\1\5\2\0\1\5\1\0\3\5\5\0"+
    "\11\5\1\64\3\5\10\0\3\5\2\0\1\5\2\0"+
    "\1\5\1\0\3\5\5\0\11\5\1\65\3\5\10\0"+
    "\3\5\2\0\1\5\32\0\1\66\12\0\1\67\33\0"+
    "\1\70\15\0\6\40\1\71\40\40\1\0\1\72\46\0"+
    "\1\5\1\0\3\5\5\0\2\5\1\73\12\5\10\0"+
    "\3\5\2\0\1\5\2\0\1\5\1\0\3\5\5\0"+
    "\6\5\1\74\6\5\10\0\3\5\2\0\1\5\2\0"+
    "\1\5\1\0\3\5\5\0\15\5\10\0\2\5\1\75"+
    "\2\0\1\5\2\0\1\5\1\0\3\5\5\0\4\5"+
    "\1\76\10\5\10\0\3\5\2\0\1\5\2\0\1\5"+
    "\1\0\3\5\5\0\7\5\1\77\5\5\10\0\1\100"+
    "\2\5\2\0\1\5\2\0\1\5\1\0\3\5\5\0"+
    "\2\5\1\101\12\5\10\0\3\5\2\0\1\5\2\0"+
    "\1\5\1\0\3\5\5\0\1\102\10\5\1\103\3\5"+
    "\10\0\3\5\2\0\1\5\2\0\1\5\1\0\3\5"+
    "\5\0\1\104\14\5\10\0\3\5\2\0\1\5\2\0"+
    "\1\5\1\0\3\5\5\0\4\5\1\105\10\5\10\0"+
    "\3\5\2\0\1\5\2\0\1\5\1\0\3\5\5\0"+
    "\14\5\1\106\10\0\3\5\2\0\1\5\2\0\1\5"+
    "\1\0\3\5\5\0\11\5\1\107\3\5\10\0\3\5"+
    "\2\0\1\5\2\0\1\5\1\0\3\5\5\0\3\5"+
    "\1\110\11\5\10\0\3\5\2\0\1\5\10\0\1\111"+
    "\40\0\1\5\1\0\3\5\5\0\3\5\1\112\11\5"+
    "\10\0\3\5\2\0\1\5\2\0\1\5\1\0\3\5"+
    "\5\0\1\113\14\5\10\0\3\5\2\0\1\5\2\0"+
    "\1\5\1\0\3\5\5\0\7\5\1\114\5\5\10\0"+
    "\3\5\2\0\1\5\2\0\1\5\1\0\3\5\5\0"+
    "\1\115\14\5\10\0\3\5\2\0\1\5\2\0\1\5"+
    "\1\0\3\5\5\0\15\5\10\0\1\5\1\116\1\5"+
    "\2\0\1\5\2\0\1\5\1\0\3\5\5\0\15\5"+
    "\10\0\1\117\2\5\2\0\1\5\2\0\1\5\1\0"+
    "\3\5\5\0\3\5\1\120\11\5\10\0\3\5\2\0"+
    "\1\5\2\0\1\5\1\0\3\5\5\0\1\5\1\121"+
    "\13\5\10\0\3\5\2\0\1\5\2\0\1\5\1\0"+
    "\3\5\2\0\1\122\2\0\15\5\10\0\3\5\2\0"+
    "\1\5\2\0\1\5\1\0\3\5\5\0\5\5\1\123"+
    "\7\5\10\0\3\5\2\0\1\5\2\0\1\5\1\0"+
    "\3\5\5\0\1\5\1\124\13\5\10\0\3\5\2\0"+
    "\1\5\2\0\1\5\1\0\3\5\5\0\12\5\1\125"+
    "\2\5\10\0\3\5\2\0\1\5\2\0\1\5\1\0"+
    "\3\5\5\0\10\5\1\126\4\5\10\0\3\5\2\0"+
    "\1\5\2\0\1\5\1\0\3\5\5\0\7\5\1\127"+
    "\5\5\10\0\3\5\2\0\1\5\2\0\1\5\1\0"+
    "\3\5\5\0\1\5\1\130\13\5\10\0\3\5\2\0"+
    "\1\5\1\0\6\122\1\131\40\122\1\0\1\5\1\0"+
    "\3\5\5\0\7\5\1\132\5\5\10\0\3\5\2\0"+
    "\1\5\2\0\1\5\1\0\3\5\5\0\7\5\1\133"+
    "\5\5\10\0\3\5\2\0\1\5\2\0\1\5\1\0"+
    "\3\5\5\0\1\134\14\5\10\0\3\5\2\0\1\5"+
    "\2\0\1\5\1\0\3\5\5\0\10\5\1\135\4\5"+
    "\10\0\3\5\2\0\1\5\10\0\1\136\40\0\1\5"+
    "\1\0\3\5\5\0\11\5\1\137\3\5\10\0\3\5"+
    "\2\0\1\5\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2301];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\7\1\1\11\12\1\10\11\4\1\1\0"+
    "\1\11\1\0\22\1\3\11\20\1\1\11\24\1\1\11"+
    "\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	private SymbolFactory sf;
	private int lineaNum;
	private boolean debug;
	public Scanner(java.io.InputStream r, SymbolFactory sf){
		this(r);
		this.sf=sf;
		lineaNum=0;
		debug=true;
	}	


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 10: 
          { if(debug)
		System.out.println("token SUMA");
	return sf.newSymbol("SUMA",Symbols.SUMA);
          }
        case 43: break;
        case 26: 
          { if(debug)
		System.out.println("token DIFERENTE");
	return sf.newSymbol("DIFERENTE",Symbols.DIFERENTE);
          }
        case 44: break;
        case 23: 
          { if(debug)
		System.out.println("token TO");
	return sf.newSymbol("TO",Symbols.TO);
          }
        case 45: break;
        case 30: 
          { if(debug)
		System.out.println("token AND");
	return sf.newSymbol("AND",Symbols.AND);
          }
        case 46: break;
        case 32: 
          { if(debug)
		System.out.println("token ELSE");
	return sf.newSymbol("ELSE",Symbols.ELSE);
          }
        case 47: break;
        case 2: 
          { if(debug)
		System.out.println("token NUMERO");
	return sf.newSymbol("NUMERO",Symbols.NUMERO,new String(yytext()));
          }
        case 48: break;
        case 42: 
          { if(debug)
		System.out.println("token INTEGER");
	return sf.newSymbol("INTEGER",Symbols.INTEGER);
          }
        case 49: break;
        case 31: 
          { if(debug)
		System.out.println("token FOR");
	return sf.newSymbol("FOR",Symbols.FOR);
          }
        case 50: break;
        case 17: 
          { if(debug)
		System.out.println("token MAYOR");
	return sf.newSymbol("MAYOR",Symbols.MAYOR);
          }
        case 51: break;
        case 7: 
          { if(debug)
		System.out.println("token PTCO");
	return sf.newSymbol("PTCO",Symbols.PTCO);
          }
        case 52: break;
        case 5: 
          { lineaNum++;
	if(debug)
		System.out.println("token LINEANUEVA");
	return sf.newSymbol("LINEANUEVA",Symbols.LINEANUEVA);
          }
        case 53: break;
        case 12: 
          { if(debug)
		System.out.println("token DIVI");
	return sf.newSymbol("DIVI",Symbols.DIVI);
          }
        case 54: break;
        case 25: 
          { if(debug)
		System.out.println("token MENORIGUAL");
	return sf.newSymbol("MENORIGUAL",Symbols.MENORIGUAL);
          }
        case 55: break;
        case 24: 
          { if(debug)
		System.out.println("token OR");
	return sf.newSymbol("OR",Symbols.OR);
          }
        case 56: break;
        case 6: 
          { /*Salta espacios en blanco*/
          }
        case 57: break;
        case 1: 
          { System.err.println("Caracter Ilegal encontrado en analisis lexico: " + yytext() + "\n");
          }
        case 58: break;
        case 33: 
          { if(debug)
		System.out.println("token NEXT");
	return sf.newSymbol("NEXT",Symbols.NEXT);
          }
        case 59: break;
        case 39: 
          { if(debug)
		System.out.println("token FLOAT");
	return sf.newSymbol("FLOAT",Symbols.FLOAT);
          }
        case 60: break;
        case 3: 
          { if(debug)
		System.out.println("token REST");
	return sf.newSymbol("REST",Symbols.REST);
          }
        case 61: break;
        case 9: 
          { if(debug)
		System.out.println("token IGUAL");
	return sf.newSymbol("IGUAL",Symbols.IGUAL);
          }
        case 62: break;
        case 36: 
          { /* salto comentarios */
	if(debug)
		System.out.println("token COMENTARIO");
          }
        case 63: break;
        case 29: 
          { if(debug)
		System.out.println("token DIM");
	return sf.newSymbol("DIM",Symbols.DIM);
          }
        case 64: break;
        case 16: 
          { if(debug)
		System.out.println("token MENOR");
	return sf.newSymbol("MENOR",Symbols.MENOR);
          }
        case 65: break;
        case 14: 
          { if(debug)
		System.out.println("token LPARENT");
	return sf.newSymbol("LPARENT",Symbols.LPARENT);
          }
        case 66: break;
        case 19: 
          { if(debug)
        System.out.println("token CADENA");
	return sf.newSymbol("CADENA",Symbols.CADENA,new String(yytext()));
          }
        case 67: break;
        case 27: 
          { if(debug)
		System.out.println("token MAYORIGUAL");
	return sf.newSymbol("MAYORIGUAL",Symbols.MAYORIGUAL);
          }
        case 68: break;
        case 4: 
          { if(debug)
		System.out.println("token IDENTIFICADOR");
	return sf.newSymbol("IDENTIFICADOR",Symbols.IDENTIFICADOR,new String(yytext()));
          }
        case 69: break;
        case 28: 
          { if(debug)
		System.out.println("token END");
	return sf.newSymbol("END",Symbols.END);
          }
        case 70: break;
        case 38: 
          { if(debug)
		System.out.println("token INPUT");
	return sf.newSymbol("INPUT",Symbols.INPUT);
          }
        case 71: break;
        case 13: 
          { if(debug)
		System.out.println("token POTE");
	return sf.newSymbol("POTE",Symbols.POTE);
          }
        case 72: break;
        case 34: 
          { if(debug)
		System.out.println("token STEP");
	return sf.newSymbol("STEP",Symbols.STEP);
          }
        case 73: break;
        case 18: 
          { /*Salto comentarios*/
	if(debug)
		System.out.println("token COMENTARIO");
	//return sf.newSymbol("COMENTARIO",Symbols.COMENTARIO);
          }
        case 74: break;
        case 21: 
          { if(debug)
		System.out.println("token IF");
	return sf.newSymbol("IF",Symbols.IF);
          }
        case 75: break;
        case 22: 
          { if(debug)
		System.out.println("token AS");
	return sf.newSymbol("AS",Symbols.AS);
          }
        case 76: break;
        case 40: 
          { if(debug)
		System.out.println("token PRINT");
	return sf.newSymbol("PRINT",Symbols.PRINT);
          }
        case 77: break;
        case 37: 
          { if(debug)
		System.out.println("token ENDIF");
	return sf.newSymbol("ENDIF",Symbols.ENDIF);
          }
        case 78: break;
        case 11: 
          { if(debug)
		System.out.println("token MULT");
	return sf.newSymbol("MULT",Symbols.MULT);
          }
        case 79: break;
        case 41: 
          { if(debug)
		System.out.println("token STRING");
	return sf.newSymbol("STRING",Symbols.STRING);
          }
        case 80: break;
        case 20: 
          { if(debug)
		System.out.println("token NO");
	return sf.newSymbol("NO",Symbols.NO);
          }
        case 81: break;
        case 8: 
          { if(debug)
		System.out.println("token COMA");
	return sf.newSymbol("COMA",Symbols.COMA);
          }
        case 82: break;
        case 35: 
          { if(debug)
		System.out.println("token THEN");
	return sf.newSymbol("THEN",Symbols.THEN);
          }
        case 83: break;
        case 15: 
          { if(debug)
		System.out.println("token RPARENT");
	return sf.newSymbol("RPARENT",Symbols.RPARENT);
          }
        case 84: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	return sf.newSymbol("EOF",Symbols.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
