
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 02 14:06:30 VET 2011
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int LPARENT = 19;
  public static final int RPARENT = 20;
  public static final int NUMERO = 12;
  public static final int MULT = 15;
  public static final int INPUT = 27;
  public static final int DIFERENTE = 36;
  public static final int INTEGER = 7;
  public static final int FOR = 28;
  public static final int NOT = 39;
  public static final int AND = 37;
  public static final int IDENTIFICADOR = 5;
  public static final int MENORIGUAL = 32;
  public static final int IGUAL = 11;
  public static final int OR = 38;
  public static final int UNTIL = 48;
  public static final int PTCO = 26;
  public static final int SUMA = 13;
  public static final int LOOP = 47;
  public static final int NEXT = 31;
  public static final int IF = 40;
  public static final int MAYORIGUAL = 34;
  public static final int DIM = 4;
  public static final int EOF = 0;
  public static final int LINEANUEVA = 49;
  public static final int error = 1;
  public static final int COMA = 10;
  public static final int WEND = 45;
  public static final int POTE = 17;
  public static final int CADENA = 25;
  public static final int CLS = 50;
  public static final int MENOR = 33;
  public static final int MOD = 18;
  public static final int DIVI = 16;
  public static final int MAYOR = 35;
  public static final int ENDIF = 43;
  public static final int REST = 14;
  public static final int ELSE = 42;
  public static final int SIGNO = 23;
  public static final int TO = 29;
  public static final int WHILE = 44;
  public static final int FLOAT = 8;
  public static final int THEN = 41;
  public static final int LCORCHE = 21;
  public static final int RCORCHE = 22;
  public static final int END = 2;
  public static final int STRING = 9;
  public static final int AS = 6;
  public static final int SUB = 3;
  public static final int DO = 46;
  public static final int PRINT = 24;
  public static final int STEP = 30;
}

