
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 15 17:40:02 VET 2011
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int LPARENT = 20;
  public static final int RPARENT = 21;
  public static final int NUMERO = 13;
  public static final int MULT = 16;
  public static final int INPUT = 28;
  public static final int DIFERENTE = 37;
  public static final int INTEGER = 8;
  public static final int FOR = 29;
  public static final int NOT = 40;
  public static final int AND = 38;
  public static final int IDENTIFICADOR = 6;
  public static final int MENORIGUAL = 33;
  public static final int IGUAL = 12;
  public static final int OR = 39;
  public static final int UNTIL = 49;
  public static final int PTCO = 27;
  public static final int SUMA = 14;
  public static final int LOOP = 48;
  public static final int NEXT = 32;
  public static final int IF = 41;
  public static final int MAYORIGUAL = 35;
  public static final int DIM = 5;
  public static final int EOF = 0;
  public static final int LINEANUEVA = 3;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int WEND = 46;
  public static final int POTE = 18;
  public static final int CADENA = 26;
  public static final int COMENTARIO = 2;
  public static final int MENOR = 34;
  public static final int MOD = 19;
  public static final int DIVI = 17;
  public static final int MAYOR = 36;
  public static final int ENDIF = 44;
  public static final int REST = 15;
  public static final int ELSE = 43;
  public static final int SIGNO = 24;
  public static final int TO = 30;
  public static final int WHILE = 45;
  public static final int FLOAT = 9;
  public static final int THEN = 42;
  public static final int LCORCHE = 22;
  public static final int RCORCHE = 23;
  public static final int END = 4;
  public static final int STRING = 10;
  public static final int AS = 7;
  public static final int DO = 47;
  public static final int PRINT = 25;
  public static final int STEP = 31;
}

