
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 12 15:21:44 VET 2011
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int LPARENT = 19;
  public static final int RPARENT = 20;
  public static final int NUMERO = 13;
  public static final int MULT = 16;
  public static final int INPUT = 24;
  public static final int DIFERENTE = 33;
  public static final int INTEGER = 8;
  public static final int FOR = 25;
  public static final int IDENTIFICADOR = 6;
  public static final int MENORIGUAL = 29;
  public static final int AND = 34;
  public static final int IGUAL = 12;
  public static final int OR = 35;
  public static final int PTCO = 23;
  public static final int SUMA = 14;
  public static final int NEXT = 28;
  public static final int IF = 37;
  public static final int MAYORIGUAL = 31;
  public static final int DIM = 5;
  public static final int EOF = 0;
  public static final int LINEANUEVA = 3;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int POTE = 18;
  public static final int CADENA = 22;
  public static final int COMENTARIO = 2;
  public static final int MENOR = 30;
  public static final int DIVI = 17;
  public static final int MAYOR = 32;
  public static final int ENDIF = 40;
  public static final int REST = 15;
  public static final int ELSE = 39;
  public static final int NO = 36;
  public static final int TO = 26;
  public static final int FLOAT = 9;
  public static final int THEN = 38;
  public static final int END = 4;
  public static final int STRING = 10;
  public static final int AS = 7;
  public static final int PRINT = 21;
  public static final int STEP = 27;
}

